package com.drf.springboot.domain;

import java.io.Serializable;

public class User implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Tue Dec 26 16:52:56 GMT+08:00 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name2
     *
     * @mbggenerated Tue Dec 26 16:52:56 GMT+08:00 2017
     */
    private String name2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name1
     *
     * @mbggenerated Tue Dec 26 16:52:56 GMT+08:00 2017
     */
    private String name1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Tue Dec 26 16:52:56 GMT+08:00 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Tue Dec 26 16:52:56 GMT+08:00 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name2
     *
     * @return the value of user.name2
     *
     * @mbggenerated Tue Dec 26 16:52:56 GMT+08:00 2017
     */
    public String getName2() {
        return name2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name2
     *
     * @param name2 the value for user.name2
     *
     * @mbggenerated Tue Dec 26 16:52:56 GMT+08:00 2017
     */
    public void setName2(String name2) {
        this.name2 = name2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name1
     *
     * @return the value of user.name1
     *
     * @mbggenerated Tue Dec 26 16:52:56 GMT+08:00 2017
     */
    public String getName1() {
        return name1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name1
     *
     * @param name1 the value for user.name1
     *
     * @mbggenerated Tue Dec 26 16:52:56 GMT+08:00 2017
     */
    public void setName1(String name1) {
        this.name1 = name1;
    }
}