package com.drf.springboot.dao;

import com.drf.springboot.domain.Name;
import com.drf.springboot.domain.NameExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Tue Dec 26 16:52:56 GMT+08:00 2017
     */
    int countByExample(NameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Tue Dec 26 16:52:56 GMT+08:00 2017
     */
    int deleteByExample(NameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Tue Dec 26 16:52:56 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Tue Dec 26 16:52:56 GMT+08:00 2017
     */
    int insert(Name record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Tue Dec 26 16:52:56 GMT+08:00 2017
     */
    int insertSelective(Name record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Tue Dec 26 16:52:56 GMT+08:00 2017
     */
    List<Name> selectByExample(NameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Tue Dec 26 16:52:56 GMT+08:00 2017
     */
    Name selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Tue Dec 26 16:52:56 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") Name record, @Param("example") NameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Tue Dec 26 16:52:56 GMT+08:00 2017
     */
    int updateByExample(@Param("record") Name record, @Param("example") NameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Tue Dec 26 16:52:56 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(Name record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table name
     *
     * @mbggenerated Tue Dec 26 16:52:56 GMT+08:00 2017
     */
    int updateByPrimaryKey(Name record);
}