package com.drf.springboot.dao;

import com.drf.springboot.domain.SysUserRolesExample;
import com.drf.springboot.domain.SysUserRolesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUserRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_roles
     *
     * @mbggenerated Tue Dec 26 22:22:56 GMT+08:00 2017
     */
    int countByExample(SysUserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_roles
     *
     * @mbggenerated Tue Dec 26 22:22:56 GMT+08:00 2017
     */
    int deleteByExample(SysUserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_roles
     *
     * @mbggenerated Tue Dec 26 22:22:56 GMT+08:00 2017
     */
    int deleteByPrimaryKey(SysUserRolesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_roles
     *
     * @mbggenerated Tue Dec 26 22:22:56 GMT+08:00 2017
     */
    int insert(SysUserRolesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_roles
     *
     * @mbggenerated Tue Dec 26 22:22:56 GMT+08:00 2017
     */
    int insertSelective(SysUserRolesKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_roles
     *
     * @mbggenerated Tue Dec 26 22:22:56 GMT+08:00 2017
     */
    List<SysUserRolesKey> selectByExample(SysUserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_roles
     *
     * @mbggenerated Tue Dec 26 22:22:56 GMT+08:00 2017
     */
    int updateByExampleSelective(@Param("record") SysUserRolesKey record, @Param("example") SysUserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_roles
     *
     * @mbggenerated Tue Dec 26 22:22:56 GMT+08:00 2017
     */
    int updateByExample(@Param("record") SysUserRolesKey record, @Param("example") SysUserRolesExample example);
}